### ISSUE TITLE
date: invalid date ‘+check_os_release_critical month’

### ISSUE THREAD

**Issue by RogerSik** [hobbyquaker/check_os_release#1]
Following error I have on all Ubuntu 14.04 and 16.04 versions.
<code>
date: invalid date ‘+check_os_release_critical month’
/usr/lib/nagios/plugins/check_os_release: line 109: [: 2021-04-01: unary operator expected
OK: Support for ubuntu 16.04 ends at 2021-04-01
</code>

**Comment by hobbyquaker** [comment]
Hmm seems like you passed something not-a-number to the `-c` option. Can you show me your nagios/icinga command definition? Does it work if you just call it manually on the command line?

**Comment by RogerSik** [comment]
Was a syntax error into the icinga2 commands.conf. Thanks for your help!
