### ISSUE TITLE
machinereadable format for EOL dates

### ISSUE THREAD

**Issue by hawaiik** [hobbyquaker/check_os_release#2]
https://salsa.debian.org/debian/distro-info-data/raw/master/debian.csv
https://salsa.debian.org/debian/distro-info-data/raw/master/ubuntu.csv

**Comment by stefanor** [comment]
The recommended source for this data is the `distro-info-data` package in Debian/Ubuntu. Or, ideally, the tools and libraries from [distro-info](https://tracker.debian.org/pkg/distro-info) that parse it.

This is kept up to date in in `-updates` in Ubuntu, and in point releases (and occasionally backports) in Debian.

Please don't hit salsa.debian.org for these, that's not what it's there for.
